### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by theGhostJW** [codedownio/sandwich#23]
Hi,
I can't see a license file anywhere in your repo.
Do you have any plans to add one?
thanks
John

**Comment by thomasjm** [comment]
Hello -- every demo and package has a LICENSE file in its folder. They're all the same BSD 3 clause license.

I could add the same file at the root I guess, I'm not sure how to get GitHub to automatically display this...

**Comment by thomasjm** [comment]
Okay, I did that and now GitHub shows it on the main page. Thanks for pointing it out.

**Comment by theGhostJW** [comment]
that was the shortest lived issue I have ever posted on github :-)
