### ISSUE TITLE
Having Trouble Running Demo On Windows

### ISSUE THREAD

**Issue by theGhostJW** [codedownio/sandwich#27]
I end up with:

    PS C:\sandwich> stack run demo-landing -- --tui

    Error: While constructing the build plan, the following exceptions were encountered:

    In the dependencies for brick-0.58.1(+demos):
        unix is a library dependency, but the package provides no library
    needed due to demo-landing-0.1.0.0 -> brick-0.58.1

    In the dependencies for sandwich-0.1.0.8:
        unix is a library dependency, but the package provides no 

    needed due to demo-landing-0.1.0.0 -> sandwich-0.1.0.8

    In the dependencies for terminfo-0.4.1.4:
        base-4.14.1.0 from stack configuration does not match >=4.9 && <4.14  (latest matching version        
                      is 4.13.0.0)
    needed due to demo-landing-0.1.0.0 -> terminfo-0.4.1.4

    In the dependencies for vty-5.32:
        unix is a library dependency, but the package provides no library
    needed due to demo-landing-0.1.0.0 -> vty-5.32

    Some different approaches to resolving this:

      * Build requires unattainable version of base. Since base is a part of GHC, you most likely need to use 
        a different GHC version with the matching base.

    Plan construction failed.

[full log](https://github.com/codedownio/sandwich/files/6858603/sandwich_log.txt)

**Comment by thomasjm** [comment]
Sadly Windows is not supported at the moment due to the `vty` dependency, as you found. There's a long discussion about it here: https://github.com/jtdaugherty/vty/pull/1.

We could disable the terminal UI formatter on Windows to get it to build, but then you'd be without one of the Sandwich's signature features :). Would you be still be interested in using it on Windows in that case?

**Comment by thomasjm** [comment]
I think it will probably work if you try it on WSL, however.

**Comment by theGhostJW** [comment]
Hello @thomasjm short answer is yes

> 
> 
> Sadly Windows is not supported at the moment due to the `vty` dependency, as you found. There's a long discussion about it here: [jtdaugherty/vty#1](https://github.com/jtdaugherty/vty/pull/1).
> 
> We could disable the terminal UI formatter on Windows to get it to build, but then you'd be without one of the Sandwich's signature features :). Would you be still be interested in using it on Windows in that case?

Hello @thomasjm. Short answer: Yes. I am very interested in exploring this package. Never tried WSL and I will but it would be great to have it working out of the box (even with limitations). It would also be good to have such limitations outlined on the home page.

**Comment by thomasjm** [comment]
Okay, I'll add a note to that effect and take a look at creating a custom build for Windows.
