### ISSUE TITLE
Request for comment: brick EventM API changes

### ISSUE THREAD

**Issue by jtdaugherty** [codedownio/sandwich#62]
I'm working on an overhaul of `brick`'s `EventM` API and I'd love to get your feedback on how it might impact this project. Please see the details and post comments on https://github.com/jtdaugherty/brick/issues/379. Thanks!

**Comment by thomasjm** [comment]
Just commented!

**Comment by jtdaugherty** [comment]
Hi, folks - Brick 1.0 is out. Here are the details: https://github.com/jtdaugherty/brick/blob/master/CHANGELOG.md#10
